vocascan/vocascan-frontend

- src/Components/Button/Button.jsx
- src/Components/Button/Button.scss
- src/Components/SelectionBox/SelectionBox.jsx
- src/Components/SelectionBox/SelectionBox.scss
- src/colors.scss
- src/screens/Login.jsx
- src/screens/Login.scss
- src/screens/Register.jsx
- src/screens/SelectionScreen.jsx
- src/screens/SelectionScreen.scss
Created a button component for app wide usage.
Extendable with more variations and / or colors.
Tell me if you want t o change the button colors.
Extendable for svg icons within the button component in the future.
> Chore: button component

- package-lock.json
- package.json
- src/Components/Select/Select.jsx
- src/Components/Select/Select.scss
- src/Components/SelectionBox/SelectionBox.jsx
- src/Components/TextInput/TextInput.jsx
- src/Components/TextInput/TextInput.scss
- src/i18n/locales/en.json
- src/screens/AddLanguagePackage/AddLanguagePackage.jsx
- src/screens/AddLanguagePackage/AddLanguagePackage.scss
- src/screens/AddVocab/AddVocab.jsx
- src/screens/AddVocab/AddVocab.scss
Select Component:
AddVocab Screen:
AddLanguagePackage Screen:
> Select component

- src/App.jsx
- src/Components/Layout/AuthenticatedLayout/AuthenticatedLayout.scss
- src/Components/Nav/Nav.jsx
- src/Components/Nav/Nav.scss
- src/Components/Nav/NavButton.jsx
- src/Components/Nav/NavButton.scss
- src/Components/Nav/TopNav.jsx
- src/Components/Nav/TopNav.scss
- src/Components/Switch/Switch.jsx
- src/Components/Switch/Switch.scss
- src/i18n/locales/en.json
- src/redux/Actions/index.js
- src/redux/Actions/setting.js
- src/redux/Reducers/index.js
- src/redux/Reducers/setting.js
- src/redux/Store/index.js
- src/screens/Settings/Settings.jsx
- src/screens/Settings/Settings.scss
| Status  | Type  | Env Vars Change | Review App | Ticket |
| :---: | :---: | :---: | :--: | :--: |
| Ready | Feature | No | [Link](<Review app link here>) | [Link](<ticket link here>) |
Add animation to side nav.
Adjusted Layout for that.
Good feeling when using the side nav.
locally
Initial settings screen
Switch between side nav variations
Top nav adjustment
> Side nav animation

- src/Components/TextInput/TextInput.jsx
- src/screens/AddLanguagePackage/AddLanguagePackage.jsx
- src/screens/Login/Login.jsx
- src/screens/Login/Login.scss
- src/screens/Register/Register.jsx
- src/screens/Register/Register.scss
| Status  | Type  | Env Vars Change
| :---: | :---: | :---: |
| Ready| Feature | No
Login and register from now can submitted with enter key
locally
> Login register form

- package.json
- src/Components/ArrayTextInput/ArrayTextInput.jsx
- src/Components/ArrayTextInput/ArrayTextInput.scss
- src/Components/Button/Button.jsx
- src/Components/Button/Button.scss
- src/Components/Layout/AuthenticatedLayout/AuthenticatedLayout.jsx
- src/Components/Layout/AuthenticatedLayout/AuthenticatedLayout.scss
- src/Components/Modal/Modal.scss
- src/Components/Nav/TopNav.scss
- src/Components/TextInput/TextInput.jsx
- src/Components/TextInput/TextInput.scss
- src/colors.scss
- src/i18n/locales/en.json
- src/screens/AddLanguagePackage/AddLanguagePackage.jsx
- src/screens/AddVocab/AddVocab.jsx
- src/screens/AddVocab/AddVocab.scss
- src/screens/Login/Login.jsx
- src/screens/Register/Register.jsx
- src/utils/constants.js
| Status  | Type  | Env Vars Change 
| :---: | :---: | :---: 
| Ready| Feature | No 
Add an ArrayTextInput Component.
Add ArrayTextInput to AddVocab screen.
locally
> Add vocab variable translations

- src/utils/api.js
- src/utils/constants.js
| Status  | Type  | Env Vars Change |
| :---: | :---: | :---: |
| Ready | Hotfix | No |
Adjust api routs of the desktop app.
locally
> User routes

- .github/pull_request_template.md
- .github/workflows/pullrequest.yml
| :white_check_mark: Ready | Refactor |
- pull request workflow does not comment the same message twice
- moved pull request template ti .github folder
I've testet this in my fork.
> improved github workflow

- .github/workflows/release.yml
- resources/electron.js
- resources/utils/constants.js
- resources/utils/ipc.js
- resources/utils/menu.js
- resources/utils/util.js
| ✅ Ready | Feature |
- Improved window Menu
- added about dialog
Added about dialog for issue reports
With my fork
> improved menu and added about dialog

- src/Components/ConfirmDialog/ConfirmDialog.jsx
- src/screens/Profile/Profile.jsx
- src/screens/Profile/Profile.scss
| Ready| Feature |
- use confirm dialog component for delete user
- enhance confirm dialog component
> feat: add enhancements to conform dialog component

- src/Components/DirectionBox/DirectionBox.scss
- src/Components/Form/Select/Select.jsx
- src/Components/Form/Select/Select.scss
- src/Forms/GroupForm/GroupForm.jsx
- src/Forms/PackageForm/PackageForm.jsx
- src/Forms/PackageForm/PackageForm.scss
- src/Forms/VocabForm/VocabForm.jsx
- src/hooks/userCountryFlag.js
- src/screens/AddVocab/AddVocab.scss
- src/screens/Library/AllGroups/AllGroups.jsx
- src/screens/Library/AllPackages/AllPackages.jsx
- src/screens/Library/AllPackages/AllPackages.scss
| Ready| Refactor|
Use new flags package in forms and tables
> chore: use new country flags plugin in forms and tables

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- README.md
| Ready | Refactor |
**I will merge this directly into main due to the limitation, that the templates are used from main.**
- improved issue templates
- added localazy badge
fork / locally
> Issuetemplates

- src/Forms/PackageForm/PackageForm.jsx
- src/i18n/locales/en/default.json
- src/utils/constants.js
| :white_check_mark: Ready| Feature |
The foreign language in the package form is now translated to the client language version.
> feature: i18n support for foreign languages

- .prettierrc
- package-lock.json
- package.json
- src/App.jsx
- src/Components/Form/TextInput/TextInput.scss
- src/Components/Indicators/LoadingIndicator/LoadingIndicator.jsx
- src/Components/Indicators/LoadingIndicator/LoadingIndicator.scss
- src/Components/Indicators/ServerValidIndicator/ServerValidIndicator.jsx
- src/Components/Indicators/ServerValidIndicator/ServerValidIndicator.scss
- src/Components/Layout/AuthenticatedLayout/AuthenticatedLayout.jsx
- src/Components/Layout/AuthenticatedLayout/AuthenticatedLayout.scss
- src/hooks/useDebounce.js
- src/i18n/locales/en/default.json
- src/screens/Login/Login.jsx
- src/screens/Login/Login.scss
- src/screens/Register/Register.jsx
- src/screens/Settings/Settings.jsx
- src/utils/api.js
- src/utils/constants.js
|  :white_check_mark: Ready | Feature |
> Server input

- src/i18n/I18nProvider.js
| :white_check_mark: Ready | Feature |
- added polish
> added language polish

- src/Components/Form/TextInput/TextInput.jsx
- src/Components/Form/TextInput/TextInput.scss
| :white_check_mark: Ready | Feature |
> added password input visibillity toggle

- src/App.jsx
- src/Components/Layout/CleanLayout/CleanLayout.jsx
- src/Components/Layout/CleanLayout/CleanLayout.scss
| :white_check_mark: Ready  | Bug |
redirect to last page after reload
> fix: dont redirect after reload

- src/i18n/locales/en/default.json
- src/screens/Custom/Custom.jsx
- src/screens/Progress/Progress.jsx
| :white_check_mark: Ready | Refactor |
improved i18n
> improved i18n

- resources/electron.js
- src/Components/Form/ArrayTextInput/ArrayTextInput.jsx
- src/Components/Form/Select/Select.jsx
- src/Components/Form/Select/Select.scss
- src/Components/Form/TextInput/TextInput.jsx
- src/Components/Form/TextInput/TextInput.scss
- src/Components/Indicators/ServerValidIndicator/ServerValidIndicator.jsx
- src/Components/PackageOverview/PackageOverview.scss
- src/Components/VocabCard/VocabCard.jsx
- src/Components/VocabCard/VocabCard.scss
- src/Forms/GroupForm/GroupForm.jsx
- src/Forms/PackageForm/PackageForm.jsx
- src/Forms/VocabForm/VocabForm.jsx
- src/Forms/VocabForm/VocabForm.scss
- src/screens/AddVocab/AddVocab.jsx
- src/screens/AddVocab/AddVocab.scss
- src/screens/Guide/Guide.jsx
- src/screens/Learn/Dashboard/Dashboard.scss
- src/screens/Learn/Query/Query.jsx
- src/screens/Library/AllGroups/AllGroups.jsx
- src/screens/Login/Login.jsx
- src/screens/Register/Register.jsx
- src/utils/constants.js
| :white_check_mark: Ready | Bug |
This PR fixes existing bugs
To Do:
> Bug fixing

- src/Components/LanguageSelector/LanguageSelector.jsx
| :white_check_mark: | Hotfix |
Bug: The select options of the LanguageSelect component is not fully visible in its modal.
This PR fixes that bug.
Before
After
> fix: language selector options visibility

- .github/workflows/translations.yml
| :white_check_mark: Ready | Bug |
This PR will hopefully fix the translations workflow
> fix translations workflow

- .github/workflows/translations.yml
| :white_check_mark: Ready | Bug |
This will hopefully fix the translations workflow again and improve performance because the other modules defined in the package.json no longer needed to be installed.
> fix translations again

- .github/workflows/ci.yml
| :white_check_mark: Ready  | Feature |
This PR creates a release on main pushes and also uploads the build each time in the workflow run artifacts.
> Precompile react on main push

- src/i18n/I18nProvider.js
| :white_check_mark: Ready | Hotfix |
I uncommented the code for untranslated languages to not show them in the language selector anymore
> fix: remove untranslated languages

- src/Components/Nav/Nav.jsx
- src/Components/Nav/Nav.scss
- src/Components/Nav/NavButton.jsx
- src/Components/Nav/NavButton.scss
- src/i18n/locales/en/default.json
- src/redux/Actions/index.js
- src/redux/Actions/setting.js
- src/redux/Reducers/setting.js
- src/screens/Settings/Settings.jsx
| :white_check_mark: Ready| Hotfix |
This PR removes the fancy menu option, as it is not working with the legal links
> fix: removed fancy menu style

- CHANGELOG.md
> v1.2.1 Changelog

- public/default-themes/dark.css
- public/default-themes/light.css
- src/Components/ContributorCard/ContributorCard.jsx
- src/Components/ContributorCard/ContributorCard.scss
- src/colors.scss
- src/i18n/locales/en/default.json
- src/screens/About/About.jsx
- src/utils/constants.js
| :white_check_mark: Ready| Feature |
In this PR I have refactored the ContributorCard code, in order to add contributors without an Github account to be more flexible.
In addition to this I have added new contributors
> About page update
